### ISSUE TITLE
Bot administration features

### ISSUE THREAD

**Issue by crisbal** [crisbal/Telegram-Bot-Node#18]
We could really use some kind of admin system for the bot. Commands like /enableplugin /disableplugin

Any idea about  this is appreciated.

**Comment by CapacitorSet** [comment]
A basic roadmap:
- [x] Define a "founder" in the configuration. This is the master user.
- [x] Add plugins as needed (eg. for /enableplugin and /disableplugin). They will simply read the incoming message and check with Auth to see if they were sent by an admin or not.

**Comment by CapacitorSet** [comment]
Both tasks were accomplished (#79,  #82), closing this.
