### ISSUE TITLE
Documentation & Readme

### ISSUE THREAD

**Issue by crisbal** [crisbal/Telegram-Bot-Node#19]
Documentation needs a serious overhaul. We need some kind of tutorial on how to create plugins, especially now that I introduced some stuff, like databases, hidden plugins and more.

**Comment by CapacitorSet** [comment]
Partly fixed in 1f78be49368e0cd17647d8608a5f195ffb1f9a0f.

**Comment by crisbal** [comment]
Very very far from complete but it's a start

**Comment by CapacitorSet** [comment]
The wiki is rather complete now. Can we close this issue, @crisbal?
