### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by crisbal** [crisbal/Telegram-Bot-Node#24]
It would be cool to have some kind of automated installer for the project.

Something like "./installer.sh" which will take care of everything needed (enable/disable plugins, ask for api key) and much more.

What do you think?

**Comment by blackdev1l** [comment]
We could use npm as starting point

**Comment by CapacitorSet** [comment]
Working on this. I'll make a script with [`read`](https://www.npmjs.com/package/read), which is the same module used for `npm init`.

**Comment by CapacitorSet** [comment]
TODO (as discussed on chat): figure out how to fetch metadata from plugins when they require missing modules.

**Comment by CapacitorSet** [comment]
Closed in b639afe.
