### ISSUE TITLE
Redis requirement?

### ISSUE THREAD

**Issue by phillipadsmith** [crisbal/Telegram-Bot-Node#26]
Howdy,

I started developing a single-purpose bot based on much of the work that you've done here (thank you!), and while troubleshooting something I thought I'd check back to see what updates had been made to this project.

I see that Redis is now required and I'm curious about how it's being used and what the purpose was / is? 

Many thanks,

Phillip.

**Comment by crisbal** [comment]
Hey Phillip

Redis is required as a database. You can use redis to save and retrieve
stuff with the wrapper db.js

Take a look at some plugins (karma.js, redis.js) to find out more.

You could totally avoid redis but doing so might need some custom changes
to the code

Have a good day

Cristian
