### ISSUE TITLE
Command Syntax

### ISSUE THREAD

**Issue by phillfarrugia** [crisbal/Telegram-Bot-Node#3]
Another one to consider... what are your thoughts regarding command syntax to trigger plugins.

I know that Slack uses `/giphy <query>`, and Github's hubot uses `hubot animate me`.
Telegram's official bots also use `/command <query>`.

Having said that I really like using `image <query>` and using a regular expression flexible enough to accept multiple i.e I just wrote a script to use:
```
    this.doMessage = function(msg, reply) {
        var re = /^(img|image|\/img|\image|!img|!image)+\s+(.*)/i;
        var match = re.exec(msg.text);
```
that way a user can say `img <query>` or `/image <query>` ...and so on, yet get the same result.

We should try and make it uniform across the project. Thoughts?

**Comment by crisbal** [comment]
In my plugins I used the exclamation mark.

Telegram suggests using the slash, both [here](https://core.telegram.org/bots#commands) and [here (/setcommands)](https://core.telegram.org/bots#commands) but it is not a requirement. 

Without a prefix for the command it is quicker to write the commands, especially if you are on a mobile phone: no need to long press on a key; but if a command is too general it could triggers in unwanted situations. 

For example we have a "*twitter \<message\>*" command, without any prefix.
If I want to send a tweet i would use it in this way "twitter Hello, World!"; but what if I am in the middle of a conversation with someone and I write "twitter is fun"? This would trigger the bot and send a tweet with the message "is fun", even if it wasn't my intention.

With a prefix sign we make sure the user wants to use a command. 

I would suggest using a slash before the command, what do you think about my considerations?

**Comment by phillfarrugia** [comment]
> A command must always start with the ‘/’ symbol and may not be longer than 32 characters.

Read this from one of the pages you've linked to above. Also more that I think about it we should probably just follow the precedent from Telegram, will only make things easier moving forward.

**Comment by crisbal** [comment]
I am OK with the / and the !  But I am still not sure about not having any prefix. We could allow that if the command is very specific and we don't risk unwanted triggers.

**Comment by crisbal** [comment]
Also parameters could be split by a "-" if one parameter is made up by more than one word? Look at the TTS plugin. 

/tts what you want to say - language

Because enclosing parameters in quotes, like you do in Windows/Linux/Mac commands is a bit slower to do any I can see many users forgetting about doing it.

**Comment by crisbal** [comment]
I created this branch: https://github.com/crisbal/Node-Telegram-Bot/tree/util-module

I added a new util module and a function to parse any message and find if it is a command and if it is it get its parameters. 

It accepts both ! and /, dividing parameters by a space or by any custom character passed as a parameter. It allows to specify command variations. 

It doesn't handle commands that doesn't start with "!" and "/" but I will add that feature in the next days/hours, as well as finishing updating all the plugins and fixing some special cases.

Example of usage:

var args = util.parseCommand("!roll 25",["roll","r"]);
args -> ["roll","25"]

**Comment by phillfarrugia** [comment]
If you create a pull request from util-module into master, I'll be able to review the diff and the tests will run :)

**Comment by crisbal** [comment]
Yeah, I know. I don't think it is ready to be pushed into master, still
need a few things.

2015-08-12 13:51 GMT+02:00 Phill Farrugia <notifications@github.com>:

**Comment by phillfarrugia** [comment]
:+1:

**Comment by crisbal** [comment]
https://github.com/crisbal/Node-Telegram-Bot/pull/13 

 Take a look, the tests are passing since nothing has really changed for the tests.

**Comment by CapacitorSet** [comment]
I think no more discussion is needed, this issue can be closed.
