### ISSUE TITLE
TTS Plugin: sometimes Google blocks the request to download the audio file. 

### ISSUE THREAD

**Issue by crisbal** [crisbal/Telegram-Bot-Node#9]
Instead of an mp3 the bot gets:

"Our systems have detected unusual traffic from your computer network.  This page checks to see if it's really you sending the requests, and not a robot." They know.

Maybe fixed by setting an user agent for the request. 

I run the bot for a few weeks in the past and me and a few friends were using it a lot and this never happened.

**Comment by crisbal** [comment]
Setting a User Agent doesn't change anything.

**Comment by ch3ll0v3k** [comment]
I have same prob. Any body solution ? 
".google.com TRUE    /   FALSE   (TIME)  GOOGLE_ABUSE_EXEMPTION  ID= ( UID):TM=(TIME):C=c:IP= (IP6) -:S=(UID)-(UID)-(UID)"
I found cookie wich appers right after tts page get refreshed.
And no result. They block it by some kind if message digest. it must be atached to the browser somehow.

**Comment by crisbal** [comment]
YES! I think I fixed it! 

I had to set a custom header and add another parameter to the request url! Give it a try and let me know!

**Comment by crisbal** [comment]
Damn, it is still not working. It worked for a few tries but now it is dead! :(

**Comment by ch3ll0v3k** [comment]
For linux users, i found alternative.
#### cepstral
This one (https://www.cepstral.com/en/demos) will coast 35$! Davids voice is nice.
----
#### poco2wave
This one (poco2wave). Is a free app. Its oke, bud not best quality.

```bash
# apt-get install libttspico-utils
```

And to use:
```bash
#!/bin/bash
#pico2wave -l=de-DE -w=test.wav "$*"
pico2wave -l=en-US -w=test.wav "$*"
aplay test.wav
#rm /tmp/test.wav
#pico2wave -w lookdave.wav "Look Dave, I can see you are really upset about this." && aplay lookdave.wav

```

**Comment by ch3ll0v3k** [comment]
Another one. Only sad thing. the gap/space/pause between words is bad 

http://www.muflone.com/gespeaker/english/mbrola.html

**Comment by crisbal** [comment]
Closing this issue since there are better bots that do this job.
